a = input('Digite qualquer coisa: ')
print('O tipo primitivo desse valor é ',type(a))
print('É alfabético ? ', a.isalpha())
print('É número ? ', a.isnumeric())
print('É alfanumérico ? ', a.isalnum())
print('Só tem espaços ?', a.isspace())
print('Está em maiúsculas ?', a.isupper())
print('Está em minúsculas ?', a.islower())
print('Está capitalizada ?', a.istitle())